#!/bin/sh
# Ein Shell Script welches vor Installation des Paketes ausgeführt wird 
echo "Checking for an older version of IPTV List Updater in the system..."
if [ -d /usr/lib/enigma2/python/Plugins/Extensions/IPTV-List-Updater ]
	then
		rm -rf /usr/lib/enigma2/python/Plugins/Extensions/IPTV-List-Updater > /dev/null 2>&1
		echo "An older version of IPTV List Updater was found and removed"
		echo "Proceeding to installation..."
	else
		echo "IPTV List Updater was not found in the system"
		echo "Proceeding to installation..."
fi
exit 0
